server:
  port: 8080

default:
  photo:
    catalog: src/main/resources/photo
    user: src/main/resources/photo/default/default.jpg

spring:
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: iso

  datasource:
    url: jdbc:postgresql://localhost:5432/users_storage
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    user: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/users_storage
    default-schema: public

  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        default_schema: public
    show-sql: true